"""
ABSIP / RAKSHAK — Backend API Server
Member 1: Backend Lead

Serves the data generated by generate_data.py (data/*.json) and the
threat-scoring logic from backend/intelligence/threat_engine.py
through a REST API that the frontend (frontend/src/api/*.js) expects.

Run:
    uvicorn backend.main:app --reload --port 8000
"""

import json
import sys
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

# ─────────────────────────────────────────────
# PATHS
# ─────────────────────────────────────────────

ROOT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT_DIR / "data"

sys.path.append(str(Path(__file__).resolve().parent))
from intelligence.threat_engine import assess_threat  # noqa: E402

# ─────────────────────────────────────────────
# APP SETUP
# ─────────────────────────────────────────────

app = FastAPI(title="RAKSHAK / ABSIP API", version="1.0.0")

# Frontend runs on Vite's default dev port(s); allow local dev origins.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:3000",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ─────────────────────────────────────────────
# DATA LOADING HELPERS
# ─────────────────────────────────────────────

def _load(filename: str) -> list:
    path = DATA_DIR / filename
    if not path.exists():
        raise HTTPException(status_code=500, detail=f"Data file missing: {filename}")
    with open(path, "r") as f:
        return json.load(f)


def _find_by_id(records: list, id_field: str, id_value: str) -> Optional[dict]:
    return next((r for r in records if str(r.get(id_field)) == str(id_value)), None)


# ─────────────────────────────────────────────
# HEALTH
# ─────────────────────────────────────────────

@app.get("/")
def root():
    return {"service": "RAKSHAK / ABSIP API", "status": "online"}


@app.get("/health")
def health():
    return {"status": "ok"}


# ─────────────────────────────────────────────
# SECTORS  → frontend/src/api/sectorApi.js
# ─────────────────────────────────────────────

@app.get("/sectors")
def get_sectors():
    return _load("sectors.json")


@app.get("/sectors/{sector_id}")
def get_sector_by_id(sector_id: str):
    sector = _find_by_id(_load("sectors.json"), "sector_id", sector_id)
    if not sector:
        raise HTTPException(status_code=404, detail=f"Sector {sector_id} not found")
    return sector


# ─────────────────────────────────────────────
# ALERTS  → frontend/src/api/alertApi.js
# ─────────────────────────────────────────────

@app.get("/alerts")
def get_alerts():
    return _load("alerts.json")


@app.get("/alerts/{alert_id}")
def get_alert_by_id(alert_id: str):
    alert = _find_by_id(_load("alerts.json"), "alert_id", alert_id)
    if not alert:
        raise HTTPException(status_code=404, detail=f"Alert {alert_id} not found")
    return alert


# ─────────────────────────────────────────────
# SUPPORTING DATA (used by Dashboard / Surveillance / Personnel / Reports)
# ─────────────────────────────────────────────

@app.get("/incidents")
def get_incidents():
    return _load("incidents.json")


@app.get("/incidents/{incident_id}")
def get_incident_by_id(incident_id: str):
    incident = _find_by_id(_load("incidents.json"), "incident_id", incident_id)
    if not incident:
        raise HTTPException(status_code=404, detail=f"Incident {incident_id} not found")
    return incident


@app.get("/patrols")
def get_patrols():
    return _load("patrols.json")


@app.get("/patrols/{patrol_id}")
def get_patrol_by_id(patrol_id: str):
    patrol = _find_by_id(_load("patrols.json"), "patrol_id", patrol_id)
    if not patrol:
        raise HTTPException(status_code=404, detail=f"Patrol {patrol_id} not found")
    return patrol


@app.get("/patrol-logs")
def get_patrol_logs():
    return _load("patrol_logs.json")


@app.get("/sensors")
def get_sensors():
    return _load("sensors.json")


@app.get("/sensors/{sensor_id}")
def get_sensor_by_id(sensor_id: str):
    sensor = _find_by_id(_load("sensors.json"), "sensor_id", sensor_id)
    if not sensor:
        raise HTTPException(status_code=404, detail=f"Sensor {sensor_id} not found")
    return sensor


@app.get("/weather")
def get_weather():
    return _load("weather.json")


@app.get("/weather/{sector_id}")
def get_weather_by_sector(sector_id: str):
    weather = _find_by_id(_load("weather.json"), "sector_id", sector_id)
    if not weather:
        raise HTTPException(status_code=404, detail=f"Weather for sector {sector_id} not found")
    return weather


# ─────────────────────────────────────────────
# DASHBOARD SUMMARY (aggregate stats for Dashboard page)
# ─────────────────────────────────────────────

@app.get("/dashboard/summary")
def dashboard_summary():
    sectors = _load("sectors.json")
    alerts = _load("alerts.json")
    incidents = _load("incidents.json")
    patrols = _load("patrols.json")

    open_alerts = [a for a in alerts if a.get("alert_status") == "open"]
    level_counts = {}
    for a in alerts:
        level_counts[a.get("threat_level", "Unknown")] = level_counts.get(a.get("threat_level", "Unknown"), 0) + 1

    return {
        "total_sectors": len(sectors),
        "active_threat_sectors": len([s for s in sectors if s.get("active_threat_designation")]),
        "total_alerts": len(alerts),
        "open_alerts": len(open_alerts),
        "threat_level_breakdown": level_counts,
        "total_incidents": len(incidents),
        "active_patrols": len([p for p in patrols if p.get("status") == "Active"]),
        "total_patrols": len(patrols),
    }


# ─────────────────────────────────────────────
# THREAT SCORING  → uses backend/intelligence/threat_engine.py
# ─────────────────────────────────────────────

@app.post("/threat-assessment")
def threat_assessment(payload: dict):
    """
    Run a detection event through the threat scoring engine.

    Body:
        {
            "sector_id": "S001",
            "confidence": 0.9,
            "event": {
                "human_detected": "...",
                "vehicle_detected": "...",
                "visibility": "...",
                "weather": "...",
                "historical_risk": 5,
                "last_patrol_hours": 2.0
            }
        }
    """
    sector_id = payload.get("sector_id")
    event = payload.get("event")
    confidence = payload.get("confidence", 1.0)

    if not sector_id or not event:
        raise HTTPException(status_code=422, detail="sector_id and event are required")

    return assess_threat(sector_id=sector_id, event=event, confidence=confidence)


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
